#!/bin/bash

IMAGE_NAME="development.blog.nasustim.com"

image_builded=$(docker image ls | grep "$IMAGE_NAME")
if [ -z "$image_builded" ]; then
  echo "image building..."
  docker build -t "$IMAGE_NAME" .
fi

docker run --rm -v $(pwd):/work -it -p 1313:1313 "$IMAGE_NAME" $*
